
name: Build and test

on:
  pull_request:
    branches: [ master, master-2.8.x ]
  push:
    branches: [ master, master-2.8.x ]

jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    with:
      timeout: 180
    secrets: inherit
